import SocialLinks from "../components/SocialLinks"; // Import the SocialLinks component
import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AudioScribe by Adi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Link to the sound.png as Favicon */}
        <link rel="icon" href="/sound.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Ensure SocialLinks is displayed in the top-right corner on desktop and bottom center on mobile */}
        <div className="fixed top-4 right-4 z-50 lg:block hidden"> {/* Visible on desktop */}
          <SocialLinks />
        </div>
        <div className="fixed bottom-4 left-1/2 transform -translate-x-1/2 z-50 lg:hidden block"> {/* Visible on mobile */}
          <SocialLinks />
        </div>
        {children}
      </body>
    </html>
  );
}
